<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ApiEndpoints" Version="4.1.0" />
    <PackageReference Include="Ardalis.ListStartupServices" Version="1.1.4" />
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Ardalis.Result.AspNetCore" Version="10.0.0" />
    <PackageReference Include="FastEndpoints" Version="5.30.0" />
    <PackageReference Include="FastEndpoints.ApiExplorer" Version="2.3.0" />
    <PackageReference Include="FastEndpoints.Swagger.Swashbuckle" Version="2.3.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdminLibrary.Admin.Infrastructure\AdminLibrary.Admin.Infrastructure.csproj" />
  </ItemGroup>

</Project>
